export function buildSpeedMeterMatchPayload({
  status,
  visibility,
  duoName,
  leftName,
  rightName,
  leftPhoto,
  rightPhoto,
  leftRadarEnabled,
  rightRadarEnabled,
  timeLeft,
  clockStartedAtMs,
  clockAccumulatedMs,
  leftHits,
  rightHits,
  ballDropEvents,
  totalScore,
  leftRawScore,
  rightRawScore,
  leftEffectiveScore,
  rightEffectiveScore,
  ballDrops,
  freeBallDrops,
  distanceMeters,
  matchDurationMinutes,
  warmupDurationMinutes,
  scoringMode,
  balanceEnabled,
  continuityEnabled,
  powerEnabled,
  minScoringSpeed,
  countBallDrops,
  ownerUserId,
  ownerEmail,
  ownerName,
}) {
  return {
    game_status: status,
    visibility,
    duo_name: duoName,
    left_name: leftName,
    right_name: rightName,
    left_photo: leftPhoto,
    right_photo: rightPhoto,
    player_left_radar_enabled: leftRadarEnabled,
    player_right_radar_enabled: rightRadarEnabled,
    time_left: timeLeft,
    clock_started_at_ms: clockStartedAtMs,
    clock_accumulated_ms: clockAccumulatedMs,
    left_hits: leftHits,
    right_hits: rightHits,
    ball_drop_events: ballDropEvents,
    total_score: totalScore,
    left_raw_score: leftRawScore,
    right_raw_score: rightRawScore,
    left_effective_score: leftEffectiveScore,
    right_effective_score: rightEffectiveScore,
    ball_drops: ballDrops,
    free_ball_drops: freeBallDrops,
    distance_meters: distanceMeters,
    match_duration_minutes: matchDurationMinutes,
    warmup_duration_minutes: warmupDurationMinutes,
    scoring_mode: scoringMode,
    balance_enabled: balanceEnabled,
    continuity_enabled: continuityEnabled,
    power_enabled: powerEnabled,
    min_scoring_speed: minScoringSpeed,
    count_ball_drops: countBallDrops,
    owner_user_id: ownerUserId,
    owner_email: ownerEmail,
    owner_name: ownerName,
  };
}
